version: "3.7"


services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/opt/app/src"
      - "./frontend/public:/opt/app/public"
